# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T19:03:11+00:00



import argparse
import json
import os
from typing import *
from typing import Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity

from models import LatestBaseCurrencyGetResponse, LatestBaseCurrencyGetResponse1

app = MCPProxy(
    description='Fetch the latest currency exchange rates via API. ExchangeRate-API is free and unlimited.',
    termsOfService='https://www.exchangerate-api.com/terms',
    title='ExchangeRate-API',
    version='4',
    servers=[
        {
            'description': 'No authentication endpoint. Returns latest exchange rates and some metadata.',
            'url': 'https://api.exchangerate-api.com/v4',
        }
    ],
)


@app.get('/latest/{base_currency}', tags=['currency_exchange_transactions'])
def get_latest__base_currency(base_currency: str):
    """
    Returns latest exchange rates in parameter-supplied base currency.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
