# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T19:03:11+00:00

from __future__ import annotations

from typing import Dict, Optional

from pydantic import BaseModel, Field


class LatestBaseCurrencyGetResponse(BaseModel):
    base: Optional[str] = Field(
        None,
        description='The currency code you supplied as base in your request',
        examples=['USD'],
    )
    date: Optional[str] = Field(
        None, description='The date these exchange rates are for'
    )
    rates: Optional[Dict[str, float]] = Field(
        None, description='Each supported currency code in terms of the base currency'
    )
    time_last_updated: Optional[int] = Field(
        None,
        description='The epoch time this set of exchange rates was generated',
        examples=[1556293443],
    )


class LatestBaseCurrencyGetResponse1(BaseModel):
    error_type: Optional[str] = None
    result: Optional[str] = None
